from __future__ import annotations

from pathlib import Path

from langchain_core.tools import BaseTool
from pydantic import BaseModel

from academic_figure_agent.schemas import DatasetSummary, FigureRequest, FigureSpec


class CodeGenerationInput(BaseModel):
    spec: dict
    request: dict
    dataset: dict
    output_dir: str


class CodeGenerationTool(BaseTool):
    name: str = "figure_code_generation"
    description: str = "Generate reproducible Python, R, LaTeX, and Mermaid source files from a FigureSpec."
    args_schema: type[BaseModel] = CodeGenerationInput

    def _run(self, spec: dict, request: dict, dataset: dict, output_dir: str) -> dict[str, str]:
        return generate_code_bundle(
            FigureSpec.model_validate(spec),
            FigureRequest.model_validate(request),
            DatasetSummary.model_validate(dataset),
            Path(output_dir),
        )


def generate_code_bundle(
    spec: FigureSpec,
    request: FigureRequest,
    dataset: DatasetSummary,
    output_dir: Path,
) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    spec_path = output_dir / "figure_config.json"
    spec_path.write_text(spec.model_dump_json(indent=2), encoding="utf-8")
    data_path = dataset.normalized_path
    generated: dict[str, str] = {}

    writers = {
        "python": ("figure.py", _python_source(spec_path, data_path, output_dir, request)),
        "r": ("figure.R", _r_source(spec, data_path)),
        "latex": ("figure.tex", _latex_source(spec, data_path)),
        "mermaid": ("figure.mmd", _mermaid_source(spec)),
    }
    for language in request.code_formats:
        filename, content = writers[language]
        path = output_dir / filename
        path.write_text(content, encoding="utf-8")
        generated[language] = str(path)
    return generated


def _python_source(spec_path: Path, data_path: Path | None, output_dir: Path, request: FigureRequest) -> str:
    return (
        "from pathlib import Path\n\n"
        "from academic_figure_agent.runtime.renderer import render_from_files\n\n"
        "if __name__ == '__main__':\n"
        f"    render_from_files(spec_path=Path({str(spec_path)!r}), "
        f"data_path={('None' if data_path is None else 'Path(' + repr(str(data_path)) + ')')}, "
        f"output_dir=Path({str(output_dir)!r}), formats={request.export_formats!r}, "
        f"languages={request.languages!r})\n"
    )


def _r_source(spec: FigureSpec, data_path: Path | None) -> str:
    if data_path is None or spec.figure_type in {"flowchart", "image_panel"}:
        return "# This figure type is rendered by the generated Python or Mermaid source.\n"
    path = data_path.as_posix()
    geom = {
        "line": "geom_line() + geom_point()",
        "bar": "geom_col(position = 'dodge')",
        "scatter": "geom_point()",
        "box": "geom_boxplot()",
        "heatmap": "geom_tile()",
    }.get(spec.figure_type, "geom_point()")
    color = f", color = `{spec.series}`" if spec.series else ""
    fill = f", fill = `{spec.series}`" if spec.series and spec.figure_type in {"bar", "box"} else ""
    return f'''library(ggplot2)
data <- read.csv("{path}", check.names = FALSE)
p <- ggplot(data, aes(x = `{spec.x}`, y = `{spec.y}`{color}{fill})) +
  {geom} +
  theme_classic(base_size = 9) +
  labs(title = "{spec.title.en}", x = "{spec.xlabel.en}", y = "{spec.ylabel.en}")
ggsave("figure_r.pdf", p, width = {spec.width_inches}, height = {spec.height_inches})
'''


def _latex_source(spec: FigureSpec, data_path: Path | None) -> str:
    if data_path is None or not spec.x or not spec.y:
        return "% This figure type has no tabular PGFPlots representation. Use figure.mmd or figure.py.\n"
    return f"""\\documentclass[tikz,border=2pt]{{standalone}}
\\usepackage{{pgfplots}}
\\pgfplotsset{{compat=1.18}}
\\begin{{document}}
\\begin{{tikzpicture}}
\\begin{{axis}}[
  width={spec.width_inches}in, height={spec.height_inches}in,
  title={{{spec.title.en}}}, xlabel={{{spec.xlabel.en}}}, ylabel={{{spec.ylabel.en}}},
  grid=major, legend style={{draw=none}}
]
\\addplot table [x={spec.x}, y={spec.y}, col sep=comma] {{{data_path.as_posix()}}};
\\end{{axis}}
\\end{{tikzpicture}}
\\end{{document}}
"""


def _mermaid_source(spec: FigureSpec) -> str:
    if spec.figure_type != "flowchart" or not spec.nodes:
        return "%% Mermaid is applicable to flowcharts. The primary figure is generated by figure.py.\n"
    lines = ["flowchart LR"]
    for node in spec.nodes:
        label = (node.label.en or node.label.zh).replace('"', "'")
        lines.append(f'    {node.id}["{label}"]')
    for edge in spec.edges:
        label = edge.label.en or edge.label.zh
        connector = f"-->|{label}|" if label else "-->"
        lines.append(f"    {edge.source} {connector} {edge.target}")
    return "\n".join(lines) + "\n"
