"""包级常量：run_scope、图运行状态、各图 phase 字面量。

完整枚举类型将由 schemas 层承载；此处仅提供与配置无关的字符串常量，
供图实现、测试与 CLI 引用，避免魔法字符串散落。
"""

from __future__ import annotations

# ---- 包元信息 ----
PACKAGE_NAME = "langgraph-agent"
DEFAULT_VERSION = "0.1.0"

# ---- run_scope（WorkspaceTaskState / FinalizeState）----
RUN_SCOPE_TASK_INIT = "TASK_INIT"
RUN_SCOPE_FINALIZE = "FINALIZE"

# ---- GraphRunStatus 字面量（对齐 backend/app/schemas/run.py）----
STATUS_PENDING = "PENDING"
STATUS_RUNNING = "RUNNING"
STATUS_WAITING_USER = "WAITING_USER"
STATUS_SUCCEEDED = "SUCCEEDED"
STATUS_FAILED_RETRYABLE = "FAILED_RETRYABLE"
STATUS_FAILED_FINAL = "FAILED_FINAL"
STATUS_SUPERSEDED = "SUPERSEDED"
STATUS_CANCELLED = "CANCELLED"

ACTIVE_RUN_STATUSES: frozenset[str] = frozenset(
    {
        STATUS_PENDING,
        STATUS_RUNNING,
        STATUS_WAITING_USER,
    }
)

# ---- 通用 phase ----
PHASE_PENDING = "PENDING"
PHASE_SUCCEEDED = "SUCCEEDED"
PHASE_REUSED = "REUSED"
PHASE_BLOCKED = "BLOCKED"

# ---- WorkspaceTaskGraph phase ----
PHASE_EXTRACT_PARTIES_AND_ITEMS = "EXTRACT_PARTIES_AND_ITEMS"
PHASE_SPLIT_SUGGESTIONS = "SPLIT_SUGGESTIONS"
PHASE_CONFIRM_SUGGESTIONS = "CONFIRM_SUGGESTIONS"
PHASE_DETECT_RELATIONS = "DETECT_RELATIONS"
PHASE_CONFIRM_RELATIONS = "CONFIRM_RELATIONS"
PHASE_PERSIST_AND_READY = "PERSIST_AND_READY"
PHASE_READY = "READY"
PHASE_PARSE_MANUSCRIPT = "PARSE_MANUSCRIPT"
PHASE_GENERATE_BASELINE_CARDS = "GENERATE_BASELINE_CARDS"
PHASE_CONFIRM_BASELINE = "CONFIRM_BASELINE"
PHASE_PERSIST_BASELINE = "PERSIST_BASELINE"

# ---- AnalysisGraph phase ----
PHASE_LOAD_SUGGESTION = "LOAD_SUGGESTION"
PHASE_CLASSIFY = "CLASSIFY"
PHASE_CONFIRM_CLASSIFICATION = "CONFIRM_CLASSIFICATION"
PHASE_EVIDENCE = "EVIDENCE"
PHASE_RETRIEVE_EVIDENCE = "RETRIEVE_EVIDENCE"
PHASE_JUDGE_COVERAGE = "JUDGE_COVERAGE"
PHASE_ASSESS_PRIORITY = "ASSESS_PRIORITY"
PHASE_RECOMMEND_ACTIONS = "RECOMMEND_ACTIONS"
PHASE_CONFIRM_FACTS = "CONFIRM_FACTS"
PHASE_PERSIST_ANALYSIS = "PERSIST_ANALYSIS"

# ---- ReplyGraph phase ----
PHASE_CHECK_ANALYSIS_READY = "CHECK_ANALYSIS_READY"
PHASE_BLOCKED_ANALYSIS = "BLOCKED_ANALYSIS"
PHASE_INTERPRET_CLAIM = "INTERPRET_CLAIM"
PHASE_RECOMMEND_STRATEGY = "RECOMMEND_STRATEGY"
PHASE_CONFIRM_STRATEGY = "CONFIRM_STRATEGY"
PHASE_BUILD_RESPONSE_FACTS = "BUILD_RESPONSE_FACTS"
PHASE_CONFIRM_RESPONSE_FACTS = "CONFIRM_RESPONSE_FACTS"
PHASE_GENERATE_DRAFT = "GENERATE_DRAFT"
PHASE_CONSISTENCY_CHECK = "CONSISTENCY_CHECK"
PHASE_PERSIST_AND_REVIEW = "PERSIST_AND_REVIEW"
PHASE_REVIEW_DRAFT = "REVIEW_DRAFT"
PHASE_PERSIST_REVIEW_DECISION = "PERSIST_REVIEW_DECISION"

# ---- FinalizeGraph phase ----
PHASE_ROUTE_FINALIZE = "ROUTE_FINALIZE"
PHASE_GENERATE_FINAL = "GENERATE_FINAL"

# ---- 模型用途（Settings.model_for）----
MODEL_PURPOSE_SPLIT = "split"
MODEL_PURPOSE_ANALYZE = "analyze"
MODEL_PURPOSE_DRAFT = "draft"
MODEL_PURPOSE_PAPER_CARD = "paper_card"

MODEL_PURPOSES: frozenset[str] = frozenset(
    {
        MODEL_PURPOSE_SPLIT,
        MODEL_PURPOSE_ANALYZE,
        MODEL_PURPOSE_DRAFT,
        MODEL_PURPOSE_PAPER_CARD,
    }
)

# ---- 论文存储默认 ----
DEFAULT_MANUSCRIPT_MAX_BYTES = 20 * 1024 * 1024
DEFAULT_MANUSCRIPT_ALLOWED_SUFFIXES: tuple[str, ...] = (".pdf",)
